/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rifushigi;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Tessera classUnderTest = new Tessera();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
