/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tessera;

import org.tessera.command.GenerateCommand;
import picocli.CommandLine;

public class Tessera {

    public static void main(String[] args) {

        int exitCode = new CommandLine(new GenerateCommand()).execute(args);
        System.exit(exitCode);
    }
}
