/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tessera;

public class Tessera {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Tessera().getGreeting());
    }
}
