/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rifushigi;

import org.rifushigi.command.GenerateCommand;
import picocli.CommandLine;

@CommandLine.Command(
        name = "generate",
        description = "Generates personalized documents from a template and data file.",
        mixinStandardHelpOptions = true,
        version = "Tessera 1.0"
)
public class Tessera {

    public static void main(String[] args) {

        int exitCode = new CommandLine(new GenerateCommand()).execute(args);
        System.exit(exitCode);
    }
}
