/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rifushigi;

import org.rifushigi.command.GenerateCommand;
import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(
        name = "tessera",
        mixinStandardHelpOptions = true,
        version = "Tessera 1.0",
        description = "Automates certificate generation from Word templates and Excel data.",
        subcommands = {
                GenerateCommand.class,
                CommandLine.HelpCommand.class
        }
)
public class Tessera {

    private Tessera() {}

    public static void main(String[] args) {

        int exitCode = new CommandLine(new Tessera()).execute(args);
        System.exit(exitCode);
    }
}
