/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // SLF4J API
    implementation("org.slf4j:slf4j-api:2.0.12")
    // Logback as the logging implementation
    implementation("ch.qos.logback:logback-classic:1.5.13")

    // picocli for CLI parsing
    implementation("info.picocli:picocli:4.7.5")

    // Apache POI for Excel and Word document manipulation
    // For reading/writing .xlsx files
    implementation("org.apache.poi:poi-ooxml:5.4.0")
    // For accessing the core POI components
    implementation("org.apache.poi:poi:5.2.5")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.rifushigi.Tessera"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
