/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tessera;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Tessera classUnderTest = new Tessera();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
